services:
  - type: web
    name: docky-frontend
    env: static
    buildCommand: ./build-frontend.sh
    staticPublishPath: ./client/build
    envVars:
      - key: REACT_APP_API_URL
        value: https://docky-server.onrender.com 